version: '3.8'

services:
  recetario:
    build: .
    ports:
      - "1881:5000"
    volumes:
      - .:/app
      - /WDPassportGabo/Servicios/Recetario/instance:/app/instance
      - /WDPassportGabo/Servicios/Recetario/base_de_datos/recetario.db:/app/recetario.db
    environment:
      - FLASK_APP=run.py
    restart: always
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true
