version: '3.8'

services:
  recetario:
    build: .
    ports:
      - "1881:5000"
    volumes:
      - ./:/app
      - ./instance:/app/instance
      - ./baseDatos:/app/baseDatos  # base de datos persistente
    environment:
      - FLASK_APP=app/run.py
      - FLASK_ENV=development
    restart: always
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true
