version: '3.8'

services:
  recetario:
    build: .
    ports:
      - "1881:5000"
    volumes:
      - ./:/app
      - ./instance:/app/instance
      - ./data/images:/app/data/images
    environment:
      - FLASK_APP=app/run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://recetario:recetario@db:5433/recetario
    depends_on:
      - db
    restart: always
    networks:
      - nginx_net

  db:
    image: postgres:15-alpine
    command: -p 5433
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: recetario
      POSTGRES_USER: recetario
      POSTGRES_PASSWORD: recetario
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true
