version: '3.8'

services:
  recetario:
    build: .
    ports:
      - "1881:5000"
    volumes:
      - ./app:/app
      - ./instance:/app/instance
      - ./data/recetario.db:/app/recetario.db
    environment:
      - FLASK_APP=app/run.py
      - FLASK_ENV=development
    restart: always
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true
