version: '3.8'

services:
  recetario:
    build: .
    ports:
      - "1881:5000"
    volumes:
      - .:/app
      - /WDPassportGabo/recetario_app/instance:/app/instance
    environment:
      - FLASK_APP=run.py
    restart: always
